# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_first_name', models.CharField(max_length=30)),
                ('Last Name', models.CharField(max_length=30)),
                ('Where You Met Contact', models.CharField(max_length=50)),
                ('When You Met', models.DateField(verbose_name='date met')),
                ('Describe Contact', models.TextField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Contact Email', models.EmailField(max_length=50)),
                ('Contact Phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
