# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20170216_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_first_name',
            new_name='First Name',
        ),
    ]
