# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20170216_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Describe Contact',
            new_name='contact_desc',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Contact Email',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='First Name',
            new_name='contact_first_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Last Name',
            new_name='contact_last_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Contact Phone',
            new_name='contact_phone',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='When You Met',
            new_name='when_met',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Where You Met Contact',
            new_name='where_met',
        ),
    ]
