# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20170216_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_email',
            new_name='Contact Email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_phone',
            new_name='Contact Phone',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_desc',
            new_name='Describe Contact',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_first_name',
            new_name='First Name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_last_name',
            new_name='Last Name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='when_met',
            new_name='When You Met',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='where_met',
            new_name='Where You Met Contact',
        ),
    ]
